package srbn.Frontend;

import java.io.File;
import javax.swing.JTextArea;

/**
 *
 * @author ADMIN
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPane
     */
    private LineNumber ln1;
    private File file =  null;

    public EditPanel() {
        initComponents();
        ln1 = new LineNumber(inputText, 3);
        inputScrollPane.setRowHeaderView(ln1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputScrollPane = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();

        setToolTipText("");

        inputText.setColumns(20);
        inputText.setLineWrap(true);
        inputText.setRows(5);
        inputText.setTabSize(4);
        inputScrollPane.setViewportView(inputText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getInputText() {
        return inputText;
    }

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane inputScrollPane;
    private javax.swing.JTextArea inputText;
    // End of variables declaration//GEN-END:variables
}
