package srbn.Frontend;

import srbn.Frontend.Drivers.TabDriver;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import srbn.Backend.Domain.ErrorE;

import srbn.Backend.Management.SemanticDriver;
import srbn.Frontend.Drivers.TablesDriver;
import srbn.Frontend.Models.TypesTableModel;
import srbn.Frontend.Models.VarsTableModel;

/**
 * @author ADMIN
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    private TabDriver td;
    private JTree filesTree;
    private SemanticDriver sm;
    private DefaultMutableTreeNode root;
    private DefaultTreeModel treeModel;
    private TablesDriver tablesDriver;

    public MainGui() {
        initComponents();
        setLocationRelativeTo(null);
        sm = new SemanticDriver();
        root = new DefaultMutableTreeNode("Archivos Abiertos");
        treeModel = new DefaultTreeModel(root);
        filesTree = new JTree(treeModel);
        treeScrollPane.add(filesTree);
        filesTree.setVisible(true);
        td = new TabDriver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsPane = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        executeButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        showTableTypesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showSymbTableButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        filesViewsTabPane = new javax.swing.JTabbedPane();
        consoleScrollPane = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        consoleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        treeScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        newFile = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        exec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        viewRecordDet = new javax.swing.JMenuItem();
        viewArrayDet = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P1 - PASCAL VERIFIER");
        setName("MainFrame"); // NOI18N
        setResizable(false);

        toolsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        openFileButton.setText("Open file");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        newFileButton.setText("New File");
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });

        saveFileButton.setText("Save File");
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });

        showTableTypesButton.setText("Tipos");
        showTableTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTableTypesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ver tablas:");

        showSymbTableButton.setText("Simbolos");
        showSymbTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSymbTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolsPaneLayout = new javax.swing.GroupLayout(toolsPane);
        toolsPane.setLayout(toolsPaneLayout);
        toolsPaneLayout.setHorizontalGroup(
            toolsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(toolsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toolsPaneLayout.createSequentialGroup()
                        .addComponent(executeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveFileButton))
                    .addGroup(toolsPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTableTypesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showSymbTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(925, Short.MAX_VALUE))
        );
        toolsPaneLayout.setVerticalGroup(
            toolsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolsPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toolsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeButton)
                    .addComponent(openFileButton)
                    .addComponent(newFileButton)
                    .addComponent(saveFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showTableTypesButton)
                    .addComponent(jLabel1)
                    .addComponent(showSymbTableButton))
                .addGap(9, 9, 9))
        );

        filesViewsTabPane.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filesViewsTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filesViewsTabPane)
        );

        consoleTextArea.setEditable(false);
        consoleTextArea.setColumns(20);
        consoleTextArea.setLineWrap(true);
        consoleTextArea.setRows(5);
        consoleTextArea.setWrapStyleWord(true);
        consoleScrollPane.setViewportView(consoleTextArea);

        consoleLabel.setText("Console");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fileMenu.setText("File");

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Open");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        fileMenu.add(openFile);

        newFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newFile.setText("New File");
        newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileActionPerformed(evt);
            }
        });
        fileMenu.add(newFile);

        saveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveFile.setText("Save File");
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileActionPerformed(evt);
            }
        });
        fileMenu.add(saveFile);
        fileMenu.add(jSeparator4);

        exec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        exec.setText("Execute");
        exec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execActionPerformed(evt);
            }
        });
        fileMenu.add(exec);

        jMenuBar1.add(fileMenu);

        jMenu2.setText("View");

        viewRecordDet.setText("Record Details");
        viewRecordDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordDetActionPerformed(evt);
            }
        });
        jMenu2.add(viewRecordDet);

        viewArrayDet.setText("Array Details");
        viewArrayDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewArrayDetActionPerformed(evt);
            }
        });
        jMenu2.add(viewArrayDet);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(consoleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consoleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addComponent(treeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toolsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(treeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consoleLabel)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(consoleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        execute();
    }//GEN-LAST:event_executeButtonActionPerformed

    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        td.addTabWithCloseButton(filesViewsTabPane, new EditPanel(), "Nuevo Archivo");
    }//GEN-LAST:event_newFileButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        td.addTabWithContent(filesViewsTabPane, new EditPanel(), root, treeModel);
//        filesTree.repaint();
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        saveFile();
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void viewArrayDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewArrayDetActionPerformed
    }//GEN-LAST:event_viewArrayDetActionPerformed

    private void showTableTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTableTypesButtonActionPerformed
        if (tablesDriver != null) {
            tablesDriver.dispose();
            tablesDriver = null;
        }
        tablesDriver = new TablesDriver(new TypesTableModel(sm.getTypeTable().getTable()));
        tablesDriver.showTable();
    }//GEN-LAST:event_showTableTypesButtonActionPerformed

    private void showSymbTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSymbTableButtonActionPerformed
        if (tablesDriver != null) {
            tablesDriver.dispose();
            tablesDriver = null;
        }
        tablesDriver = new TablesDriver(new VarsTableModel(sm.getSymbTable().getTable()));
        tablesDriver.showTable();
    }//GEN-LAST:event_showSymbTableButtonActionPerformed

    private void viewRecordDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordDetActionPerformed
        new Details(sm.getSymbTable()).setVisible(true);
    }//GEN-LAST:event_viewRecordDetActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        td.addTabWithContent(filesViewsTabPane, new EditPanel(), root, treeModel);
    }//GEN-LAST:event_openFileActionPerformed

    private void newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileActionPerformed
        td.addTabWithCloseButton(filesViewsTabPane, new EditPanel(), "Nuevo Archivo");
    }//GEN-LAST:event_newFileActionPerformed

    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed
        saveFile();
    }//GEN-LAST:event_saveFileActionPerformed

    private void execActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execActionPerformed
        execute();
    }//GEN-LAST:event_execActionPerformed

    private void saveFile() {
        EditPanel comp = (EditPanel) filesViewsTabPane.getSelectedComponent();
        td.fileSaver(comp);
//        td.addFileToTree(comp, root, treeModel); TODO fix
//        filesTree.repaint();
    }

    private void execute() {
        EditPanel comp = (EditPanel) filesViewsTabPane.getSelectedComponent();

        try {
            if(comp == null){
                throw new ErrorE("Abre o crea un archivo para analizar");
            }
            
            if (!comp.getInputText().getText().isBlank()) {
                sm.executeAnalyzer(comp.getInputText().getText());
                consoleTextArea.setText(sm.getErrors());
                consoleTextArea.repaint();
            } else {
                throw new ErrorE("La entrada esta vacia");
            }
        } catch (Exception e) {
            consoleTextArea.setText(e.getMessage());
            consoleTextArea.repaint();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consoleLabel;
    private javax.swing.JScrollPane consoleScrollPane;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JMenuItem exec;
    private javax.swing.JButton executeButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTabbedPane filesViewsTabPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem newFile;
    private javax.swing.JButton newFileButton;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JButton openFileButton;
    private javax.swing.JMenuItem saveFile;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JButton showSymbTableButton;
    private javax.swing.JButton showTableTypesButton;
    private javax.swing.JPanel toolsPane;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JMenuItem viewArrayDet;
    private javax.swing.JMenuItem viewRecordDet;
    // End of variables declaration//GEN-END:variables
}
